// src/window/screen/Frame.svelte
<div class="frame" style={`
top: ${windowInfo.visible ? (windowInfo.fullscreen ? 0 : windowInfo.rect.y) : window.innerHeight}px;
left: ${windowInfo.fullscreen ? 0 : windowInfo.rect.x}px;
width: ${windowInfo.fullscreen ? window.innerWidth : windowInfo.rect.width}px;
height: ${windowInfo.fullscreen ? window.innerHeight - footerHeight : windowInfo.rect.height}px;
cursor: ${cursor};
z-index: ${zIndex};
border-color: ${focus ? '#3B77BC' : '#3B77BC'};
--header-height: ${windowHeaderHeight}px
`}
  on:mousedown={(e) => mouseDownHandler(windowInfo)(e)}
>
  <div class="header"
  >
    <div class="title">
      <h2>{windowInfo.title}</h2>
    </div>
    <div class="controls">
      <button on:click|stopPropagation={closeHandler} on:mousedown|stopPropagation={() => ''}>_</button>
      <button on:click|stopPropagation={fullScreenHandler} on:mousedown|stopPropagation={() => ''}>□</button>
      {#if id !== 'visualizer'}
        <button on:click|stopPropagation={killHandler} on:mousedown|stopPropagation={() => ''}>×</button>
      {/if}
    </div>
  </div>
  <section class="content">
    <Component />
  </section>
</div>

<svelte:body on:mousemove={mouseMoveHandlerWrapper} on:mouseup={mouseUpHandlerWrapper} />

<script type="ts">
import { footerHeight, windowHeaderHeight } from "../globals";
import { WindowSystem, type WindowInfo } from "../stores/WindowSystem";

import { MouseEventHandlerGenerator } from "./mouseevent";

export let id: string
export let windowInfo: WindowInfo
export let zIndex: number
export let focus: boolean
let cursor  = 'default'

let { Component } = windowInfo

const fullScreenHandler = () => {
  WindowSystem.updateWindow(id, {
    ...windowInfo,
    fullscreen: !windowInfo.fullscreen
  })
}
const closeHandler = () => {
  WindowSystem.updateWindow(id, {
    ...windowInfo,
    visible: false
  })
}
const killHandler = () => {
  WindowSystem.killWindow(id)
}

// mouse events
const {
  mouseDownHandler,
  mouseMoveHandler,
  mouseUpHandler,
  cursorGetter
} = MouseEventHandlerGenerator(id)

const mouseMoveHandlerWrapper = (e: MouseEvent) => {
  cursor = cursorGetter()
  mouseMoveHandler(windowInfo)(e)
}
const mouseUpHandlerWrapper = () => {
  mouseUpHandler()()
}

</script>

<style type="scss">
.frame {
  position: absolute;
  box-sizing: border-box;
  background: white;
  border: 7px solid;
  border-radius: 10px;

  .header {
    position: absolute;
    top: 0;
    left: 0;
    display: flex;
    justify-content: space-between;
    width: 100%;
    height: var(--header-height);
    background-color: #3b77bc;
    outline: 1px #3b77bc solid;

    h2 {
      margin: 0;
      font-size: 20px;
      color: white;
    }
  }

  .content {
    position: absolute;
    top: var(--header-height);
    left: 0;
    width: 100%;
    height: calc(100% - var(--header-height));
    overflow: hidden;
  }
}
</style>

// src/window/screen/Frame.tsx
import { Container, useTick } from '@inlet/react-pixi'
import { useContext, useEffect, useRef, useState, VFC } from 'react'
import { footerHeight, windowHeaderHeight } from '../globals'
import type { WindowInfo } from '../stores/WindowSystem'
import { MouseEventHandlerGenerator } from './mouseevent'
import { WindowSettingContext } from '../GlobalSetting'
import type { InteractionEvent } from 'pixi.js'
import { getCursorIcon, updateCursorIcon } from '../stores/cursorIcon'
import { FrameTemplate } from '../utils/FrameTemplate'

interface FrameProps {
  id: string
  windowInfo: WindowInfo
  focus: boolean
}

export const Frame: VFC<FrameProps> = ({ id, windowInfo }) => {
  const { width, height } = useContext(WindowSettingContext)
  const { title, visible, fullscreen, Component } = windowInfo

  const rect = !fullscreen
    ? windowInfo.rect
    : {
        x: 0,
        y: 0,
        width,
        height: height - footerHeight
      }

  const { windowSettings } = useContext(WindowSettingContext)

  const windowInfoRef = useRef<WindowInfo | null>(windowInfo)

  const fullScreenHandler = () => {
    windowSettings.update(id, {
      ...windowInfo,
      fullscreen: !windowInfo.fullscreen
    })
  }
  const closeHandler = () => {
    windowSettings.minimize(id)
  }
  const killHandler = () => {
    windowSettings.kill(id)
  }

  useEffect(() => {
    windowInfoRef.current = windowInfo
  }, [windowInfo])

  const [handler, setHandler] = useState<{
    mouseDownHandler:
      | ((_windowInfo: WindowInfo) => (_e: InteractionEvent) => void)
      | null
    cursorMouseMoveHandler:
      | ((_windowInfo: WindowInfo) => (_e: InteractionEvent) => void)
      | null
    mouseOverHandler: (() => void) | null
    mouseOutHandler: (() => void) | null
    getCursor: (() => string) | null
  }>({
    mouseDownHandler: null,
    cursorMouseMoveHandler: null,
    mouseOverHandler: null,
    mouseOutHandler: null,
    getCursor: null
  })

  useEffect(() => {
    const {
      mouseDownHandler,
      mouseMoveHandler,
      mouseUpHandler,
      cursorMouseMoveHandler,
      mouseOutHandler,
      mouseOverHandler,
      getCursor
    } = MouseEventHandlerGenerator(id, windowSettings, width, height)
    setHandler({
      mouseDownHandler,
      cursorMouseMoveHandler,
      mouseOverHandler,
      mouseOutHandler,
      getCursor
    })
    const mouseMoveHandlerWrapper = (e: MouseEvent) => {
      // document.body.style.cursor = cursorGetter()
      mouseMoveHandler(windowInfoRef.current || windowInfo)(e)
    }
    const mouseUpHandlerWrapper = () => {
      mouseUpHandler()()
    }

    const pixicanvas = document.getElementById('pixicanvas')
    if (!pixicanvas) return
    pixicanvas.addEventListener('mousemove', mouseMoveHandlerWrapper)
    pixicanvas.addEventListener('mouseup', mouseUpHandlerWrapper)
    return () => {
      pixicanvas.removeEventListener('mousemove', mouseMoveHandlerWrapper)
      pixicanvas.removeEventListener('mouseup', mouseUpHandlerWrapper)
    }
  }, [])

  useTick(() => {
    if (handler.getCursor && handler.getCursor() && !getCursorIcon()) {
      updateCursorIcon(handler.getCursor())
    }
  })

  return (
    <Container
      position={!visible ? [rect.x, -99999] : [rect.x, rect.y]}
      interactive
      mousedown={
        handler.mouseDownHandler
          ? handler.mouseDownHandler(windowInfo)
          : () => ''
      }
      mousemove={
        handler.cursorMouseMoveHandler
          ? handler.cursorMouseMoveHandler(windowInfo)
          : () => ''
      }
      mouseover={handler.mouseOverHandler ? handler.mouseOverHandler : () => ''}
      mouseout={handler.mouseOutHandler ? handler.mouseOutHandler : () => ''}
    >
      <FrameTemplate
        width={rect.width}
        height={rect.height}
        title={title}
        onMinimize={closeHandler}
        onMaximize={fullScreenHandler}
        onKill={id === 'visualizer' ? undefined : killHandler}
      >
        {Component ? (
          <Component
            x={rect.x}
            y={rect.y + windowHeaderHeight}
            width={rect.width}
            height={rect.height - windowHeaderHeight}
          />
        ) : (
          <Container />
        )}
      </FrameTemplate>
    </Container>
  )
}
