// src/window/screen/Screen.tsx
import { useContext } from 'react'
import { WindowSettingContext } from '../GlobalSetting'
import { Background } from './background/Background'
import { Frame } from './Frame'
import { dummyWindow } from './frames'

export const Screen = () => {
  const {
    windowSettings: { windows, windowIndices: windowIndices }
  } = useContext(WindowSettingContext)
  return (
    <>
      <Background />
      {windowIndices.map(id => (
        <Frame
          windowInfo={windows[id] || dummyWindow}
          id={id}
          focus={false}
          key={id}
        />
      ))}
    </>
  )
}

// src/window/screen/Screen.svelte
<Background />
{#each windowIndices as id, i (id)}
  <Frame windowInfo={windows[id] || dummyWindow} id={id} zIndex={i} focus={focused === id} />
{/each}

<script lang="ts">
  import Frame from '../screen/Frame.svelte'
  import Background from './background/Background.svelte'
  import { WindowSystem, type WindowInfo } from '../stores/WindowSystem'
  import { dummyWindow } from './frames';
  let windowIndices = [] as string[]
  let focused = ''
  let windows = {} as Record<string, WindowInfo>

  WindowSystem.windowIndices.subscribe(value => {
    windowIndices = value
    const visibles = windowIndices.filter(id => windows[id]?.visible)
    focused = visibles[visibles.length - 1] || ''
  })
  WindowSystem.windows.subscribe(value => {
    windows = value
    const visibles = windowIndices.filter(id => windows[id]?.visible)
    focused = visibles[visibles.length - 1] || ''
  })
</script>
